#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
polybar &
nm-applet &
emacs --daemon &

bspc monitor -d 1 2 3 4 5 

bspc config border_width         2
bspc config window_gap          40
bspc config top_padding 30
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config pointer_section1 move
bspc config pointer_section2 resize_side
bspc config pointer_section3 resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colours
bspc config normal_border_color "#838ba7"
bspc config active_border_color "#f2d5cf"
bspc config focused_border_color "#ca9ee6"
bspc config presel-feedback_colour "#fc9d63"
